name: Auto Deploy to Internal Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest code from Git
        run: |
          cd /root/stratanote
          git fetch origin
          git reset --hard origin/master

      - name: Install dependencies
        run: |
          cd /root/stratanote/_app
          npm install

      - name: Build frontend
        run: |
          cd /root/stratanote/_app
          npm run build

      - name: Restart server in PM2
        run: |
          pm2 restart stratanote
